version: '3'
services:
  tracking-server:
    build: tracking_server/
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    volumes:
      - ./tracking_server/test.db:/src/runs.db
    ports: 
      - "5000:5000"

  experiment:
    build: modeling/
    depends_on:
      - tracking-server
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    volumes:
      - ./modeling/bank_scoring.csv:/src/bank_scoring.csv
