version: '3'
services:
  tracking-server:
    image: tracking_server:latest
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_CONTAINER=${AZURE_CONTAINER}
    volumes:
      - ./tracking_server/test.db:/src/runs.db
    ports: 
      - "5000:5000"

  experiment:
    image: modeling_code
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
    volumes:
      - ./modeling/bank_scoring.csv:/src/bank_scoring.csv
