name: dvc_pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          cd dvc_hw
          pip install --upgrade pip
          pip install -r requirements.txt
          
          dvc pull
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          echo "## Results"
          cml-publish feature_plot.png --md >> report.md
          cml-send-comment report.md
