name: dvc_pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r dvc_hw/requirements.txt
          cd dvc_hw
          python preprocess.py
          python training.py
          python evaluation.py
          cat metrics.json