name: dvc_pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r dvc_hw/requirements.txt
          python dvc_hw/preprocess.py
          python dvc_hw/training.py
          python dvc_hw/evaluation.py
          cat dvc_hw/metrics.json